#pragma once


#define IOCTL_INIT_EVENT            (ULONG)CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, FILE_ALL_ACCESS)
#define IOCTL_SEND_CAPTURE_DATA     (ULONG)CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_BUFFERED, FILE_ALL_ACCESS)
//#define IOCTL_ACCEPT_RENDER_DATA    (ULONG)CTL_CODE(FILE_DEVICE_UNKNOWN, 0x902, METHOD_BUFFERED, FILE_ALL_ACCESS)

#define SYMBOL_LINK L"\\\\.\\Test"

#define REFTIMES_PER_SEC  10000000

#define RENDER_START_EVENT_NAME L"Global\\RenderStartEvent"
#define CAPTURE_START_EVENT_NAME L"Global\\CaptureStartEvent"

#define RENDER_STOP_EVENT_NAME L"Global\\RenderStopEvent"
#define CAPTURE_STOP_EVENT_NAME L"Global\\CaptureStopEvent"

const int MAX_EVENT_COUNT = 4;